#!/bin/sh

export JDBC_LIBRARY='/Users/david/Developer/OutSystems/jdbc-drivers/oracle/ojdbc8-full-12.2.0.1-jdk8/ojdbc8.jar'
export JDBC_STRING='jdbc:oracle:thin:@entelprdcleanup.cwbjmle0w8cz.us-east-1.rds.amazonaws.com:1521:ENTELPRD'
export JDBC_USER='SAPRD150568'
export JDBC_PASSWORD='Xpto1234!'
export JDBC_SCHEDULE='*/5 * * * *'
export DATA_CUSTOMER_NAME='SCML'
export DATA_LOCATION_NAME='Lisboa'
export DATA_ENVIRONMENT_NAME='Development'
export LAST_RUN_DIR='/Users/david/Developer/OutSystems/customers/scml/run'
export PATTERNS_DIR='/Users/david/Developer/OutSystems/customers/scml/patterns'
export ES_HOSTS='localhost:9200'

echo 'JDBC_LIBRARY="'$JDBC_LIBRARY'"'
echo 'JDBC_STRING="'$JDBC_STRING'"'
echo 'JDBC_USER="'$JDBC_USER'"'
echo 'JDBC_PASSWORD="'$JDBC_PASSWORD'"'
echo 'JDBC_SCHEDULE="'$JDBC_SCHEDULE'"'
echo 'DATA_CUSTOMER_NAME="'$DATA_CUSTOMER_NAME'"'
echo 'DATA_LOCATION_NAME="'$DATA_LOCATION_NAME'"'
echo 'DATA_ENVIRONMENT_NAME="'$DATA_ENVIRONMENT_NAME'"'
echo 'LAST_RUN_DIR="'$LAST_RUN_DIR'"'
echo 'PATTERNS_DIR="'$PATTERNS_DIR'"'
echo 'ES_HOSTS="'$ES_HOSTS'"'
